resolver swarm-proxy_swarm-dns-proxy valid=10s ipv6=off;

upstream test-balancer-service {
    zone test-balancer-service 64k;
    hash $http_x_request_id consistent;
    server manager-swarm.replica-000.test-balancer_test-balancer.swarm:5000 resolve;
    server worker-swarm.replica-000.test-balancer_test-balancer.swarm:5000 resolve;
}

server {
    listen 80;

    location / {
      proxy_pass http://test-balancer-service/;
      proxy_http_version 1.1;
      proxy_set_header "Connection" "";
    }
}